### ISSUE TITLE
Bad Request On Bulk Data Type Fetch

### ISSUE THREAD

**Issue by lylerolleman** [bytewisemarissa/HelpfulThings.Connect.Scryfall#5]
When I attempt to get bulk card data, I get a 400 Bad Request

Ex.
`var bulkData = await ScryfallApiClient.BulkData.GetBulkDataListingByTypeAsync(BulkTypes.DefaultCards);`

The reason for this I suspect is the BulkType enum has incorrect member values (ex. "default_cards" rather than "default-cards")

https://scryfall.com/docs/api/bulk-data/type

**Comment by bytewisemarissa** [comment]
Thats a bummer 😕 I should be able to take a look at this later today.

**Comment by bytewisemarissa** [comment]
This should be resolved with 1.5.0. Scryfall requires both a UserAgent and Accept headers now. I added some default values for this and a function on the base controller to update the UserAgent if required. Turns out the API doesn't care if its default_cards for default-cards after some testing fwiw.

**Comment by lylerolleman** [comment]
Tried out 1.5.0 and it's working like a charm now, thanks for the quick fix
